### ISSUE TITLE
Embedded structs not handled

### ISSUE THREAD

**Issue by Peltoche** [hamba/avro#100]
Hello hamba and all the commiters,

First thanks a lot for this lib, it's really great and simple to use! 

It seems that the support of embedded structs is missing. It would be great to have it in order to have the same behaviour than the standard libraries like the json Unmarshaler.

This is an exemple with some json (https://play.golang.org/p/9D_B3lXtJ0D):
```go
package main

import (
	"encoding/json"
	"fmt"
)

type commonListResponse struct {
	PageSize int `json:"page_size"`
}

type Account struct {
	Name string `json:"name"`
}

type AccountList struct {
	commonListResponse
}

const jsonBlob = `{ "page_size": 50 }`

func main() {
	alb := AccountList{}
	json.Unmarshal([]byte(jsonBlob), &alb)
	fmt.Printf("With Embedded field: %#v\n", alb)
}
```

**Comment by nrwiersma** [comment]
Hi,

Thanks for the suggestion. How are you expecting the lib to handle embedded structs? Are you expecting it to be a field or all the fields in the embedded struct to act as field in the containing struct?

**Comment by Peltoche** [comment]
I hope that it have the same behavior than the json lib. That said I don't master well the subject. I will try to find some tests or snippets with some more informations.

You can find some documentation here -> https://www.cnblogs.com/oxspirt/p/10863080.html

**Comment by eminrollic** [comment]
Hi, 

This is huge road block for us as well, I've a base data model for using in every struct and embedded that on those structs and using it with json encode like this;

```
type BaseDataModel struct {
   ID int `json:"id" avro:"id"`
}

type UserDataModel struct {
  BaseDataModel
  Name string `json:"name" avro:"name"`
}

func main(){
   u := UserDataModel{
     BaseDataModel: BaseDataModel{
      ID: 1
     },
     Name: "test",
  }

  out, _ := json.Marshall(u)
  fmt.Println(out)
}

```

This will print out:

```
{"id": 1, "name":"test"}
```

No nesting like it's a complete struct.

Now to be able to use this for avro I need to unnest all structs like this. Otherwise, I get error for `UserDataModel is missing required field id`

On reflection side, this should be easy to add as a feature but I'm not familiar with library well enough to go for it and do it quickly for my case;

For similar situation, I also use reflection on these structs for some generation;

For example, this is the code for generating avro schema from struct's tags 

All structs I've added `avro_type` to annotate for type definition. For embedded struct all I need to do recurse into same function to get the fields and problem solved.

Code Example for schema generation;

```

func GenerateAvroSchema(model interface{}) string {
	val := reflect.ValueOf(model)
	v := val.Type()

	fields := getAvroFields(model)
	schema := AvroSchema{
		Type:      "record",
		Name:      v.Name(),
		Namespace: "some.namespace",
		Fields:    fields,
	}
	st, err := json.Marshal(schema)
	if err != nil {
		log.Err(err).Msg("")
		return ""
	}
	return string(st)
}

func getAvroFields(model interface{}) []AvroField {
	fields := make([]AvroField, 0, 10)

	val := reflect.ValueOf(model)
	v := val.Type()
	for i := 0; i < val.NumField(); i++ {
		t := v.Field(i)
		if val.Field(i).Kind() == reflect.Struct {
			c := getAvroFields(val.Field(i).Interface())
			fields = append(fields, c...)
			continue
		}

		field := AvroField{
			Name: t.Tag.Get("avro"),
                         Type: t.Tag.Get("avro_type")
		}
		fields = append(fields, field)
	}
	return fields
}


```

**Comment by nrwiersma** [comment]
Would it be possible for you all to test #101 and see if it meets your needs. The parsing is a little complex so some real world tests would be good. I still have a couple tests to write but in general it seems like it functions.

**Comment by eminrollic** [comment]
wow, thanks for the fast response. I've tested it quickly, it works as expected.

**Comment by Peltoche** [comment]
I confirm, it work! Thanks a lot for this quick improvement!
