### ISSUE TITLE
Support for obtaining schema or other metadata from OCF decoder

### ISSUE THREAD

**Issue by phemmer** [hamba/avro#32]
It might be nice to be able to access the schema or other metadata from a `ocf.Decoder` object.

In my use case, I have a few thousand avro files of a few MB each, that I needed to sort on a specific field. The files had a few different schemas, but all had this one field in common. So my intent was to open the file, unmarshal all the records into a generic `map[string]interface{}`, sort based on the known field, and then marshal the results out with the exact same schema as the input.

So for my use case, accessing the schema of the decoder, so I could pass it to the new encoder would be sufficient (I implemented this in my local fork).
However as there can be other data in the metadata that might be useful to others, I suspect it would be better to expose all the metadata. Or possibly the entire `Header` object, with a helper method like `GetSchema()`.

**Comment by nrwiersma** [comment]
Hi,

Thanks for the great idea. You are correct that having access to the meta is a great idea for the `Decoder`, and likely it would be good to be able to pass meta into the `Encoder` as well. This implementation was a bit bare bones to get it up and running.

For the `Decoder` I would likely expose it with `Metadata()` and just return the map. For the `Encoder` i would likely implement an `EncoderFunc` to allow adding custom meta in. 

If you would like to contribute this, please feel free. Otherwise I can make the change.

Thanks again,
Nick
