### ISSUE TITLE
Support for generate structs from avsc file

### ISSUE THREAD

**Issue by Amb87** [hamba/avro#96]
Does it have the support for generating structs from avsc schema file? 

For example, like this: 
https://github.com/actgardner/gogen-avro

**Comment by nrwiersma** [comment]
No, it does not support this.

**Comment by Amb87** [comment]
Is this feature planned for the future?

Thanks

**Comment by nrwiersma** [comment]
I have considered the idea but have not done it as a) I have never encountered the need. In my use of Avro, my structs were multi purpose (e.g. json and avro) so generators would not work and b) I generally prefer tool-less implementations where possible.

That said, I am not against the idea but wonder which is a more common need, schema -> struct or struct -> schema.

**Comment by pedromss** [comment]
Why would generators not work for multi purpose structs? I also use the same structs and just rely on the annotations for both formats. Where I need different types I also need different structs.

I would argue that the most common need is schema -> struct **because** that's what consumers need and for every producer there can be infinite consumers. So for every time someone needs struct -> schema, probably a lot more people are going to need schema -> struct.

I would also very much like to see this feature and am glad to help out where possible. The tedious part of working with avro in Go is really to have to create the structs and **more importantly** get the types of the structs right! Generating structs from schemas **has the potential to eliminate** the human error in creating the structs.

**Comment by nrwiersma** [comment]
| Why would generators not work for multi purpose structs? I also use the same structs and just rely on the annotations for both formats. Where I need different types I also need different structs.

Every time you regenerate, it would only generate the avro tags, you would need to manually add the other tags.

I suggest to add it to the discussion I started for ideas for `v2`. This look a good candidate for this.
